import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";
import { Button } from "@/components/ui/button";
import { Bell } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-raleway",
  style: ["normal", "italic"],
  subsets: ["vietnamese"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleway.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <header className="z-99 fixed w-screen h-12 border border-b bg-background">
            <Tooltip>
              <TooltipTrigger className="my-auto" asChild>
                <Button variant="outline" size="icon" className="rounded-full border-gray-600">
                  <Bell size={18} strokeWidth={1.5} />
                </Button>
              </TooltipTrigger>
              <TooltipContent className="text-foreground bg-background border border-muted-foreground" arrow={false}>
                Thông báo
              </TooltipContent>
            </Tooltip>
          </header>
          <SidebarProvider>
            <AppSidebar/>
            {children}
          </SidebarProvider>  
        </ThemeProvider>
      </body>
    </html>
  );
}
